name: Security

permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
  schedule:
    - cron: 30 5 * * *

jobs:
  security:
    name: Audit packages
    runs-on: ubuntu-latest
    continue-on-error: True
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Audit python packages
        run: uv audit
